[package]
name = "Mirror-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
kcp2k_rust = { path = "src/transports/kcp2k/kcp2k-rust" }
bytes = "1.7.1"
byteorder = "1.5.0"
bytemuck = "1.18.0"
serde = { version = "1.0.210", features = ["derive"] }
nalgebra = "0.33.0"
encoding_rs = "0.8.34"
hex = "0.4.3"
dashmap = "6.1.0"
tklog = "0.2.1"
rust_multistack = "0.29.0"
serde_json = "1.0"
atomic = "0.6"
lazy_static = "1.5.0"
crossbeam-channel = "0.5.13"

[build]
rustflags = ["-A", "warnings"]
