[package]
name = "Mirror-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
kcp2k_rust = { path = "./src/Transports/KCP/kcp2k-rust" }
tokio = "1.40.0"
bytes = "1.7.1"
log = "0.4.22"
lazy_static = "1.5.0"
byteorder = "1.5.0"
bytemuck = "1.18.0"
